uav_parameters:
  #mass: 2.8                  # Kg
  #mass: 4.446                # Kg [with arm]
  mass: 3.407                # Kg [with ZED kit]
  arm_length: 0.36             # m
  num_of_arms: 6
  inertia:                     # Kg.m^2
    x: 0.08612
    y: 0.08962
    z: 0.16088
  moment_constant: 0.0165     # m
  thrust_constant: 2.3885e-05   # N.s^2/rad^2
  max_rotor_speed: 870         # rad/s
  gravity: 9.81                # m/s^2
  omega_to_pwm_coefficient:
    x_2: 8.12e-04
    x_1: 0.2823
    x_0: 1113
  PWM_MIN: 1075
  PWM_MAX: 1950