uav_parameters:
  mass: 9.5  # without batteries = 6.4 # Kg
  arm_length: 0.45             # m
  num_of_arms: 44
  inertia:                     # Kg.m^2
    x: 0.2
    y: 0.2
    z: 0.3
  moment_constant: 0.0202        # m
  thrust_constant: 9.68e-05    # N.s^2/rad^2
  max_rotor_speed: 730        # rad/s
  gravity: 9.81                # m/s^2
  omega_to_pwm_coefficient:
    x_2: 0.0007979
    x_1: 0.5009
    x_0: 1122
  PWM_MIN: 1075
  PWM_MAX: 1950
  input_scaling: 630
  zero_position_armed: 100