uav_parameters:
  mass: 11.7  # without batteries = 6.4 # Kg
  arm_length: 0.45             # m
  num_of_arms: 44
  inertia:                     # Kg.m^2
    x: 0.2
    y: 0.2
    z: 0.3
  moment_constant: 0.0202        # m
  thrust_constant: 6.9e-05    # N.s^2/rad^2
  max_rotor_speed: 730        # rad/s
  gravity: 9.81                # m/s^2
  omega_to_pwm_coefficient:
    x_2: 0.0007979
    x_1: 0.5009
    x_0: 1122
  PWM_MIN: 1075
  PWM_MAX: 1950
  input_scaling: 630
  zero_position_armed: 100
  voltage_compensation:
    model_slope: -0.642210
    model_max_voltage: 25.2
    model_max_voltage_percentage_constant: 0.94178
    model_max_voltage_compensation: 0.1
    use_voltage_compensation: true
