K_p_x: 1.00
K_p_y: 1.00
K_p_z: 5.00
K_v_x: 0.70
K_v_y: 0.70
K_v_z: 2.00
K_R_x: 0.10
K_R_y: 0.10
K_R_z: 0.0035
K_w_x: 0.1
K_w_y: 0.1
K_w_z: 0.025
K_o_x: 0.5
K_o_y: 0.4
K_o_z: 0.3
D_x: 0.2
D_y: 0.15
D_z: 0.1