name: Setup and build packages

# To manually run the workflow on GH, use the workflow_dispatch event trigger
# on: workflow_dispatch

# To automatically run on every push to GH, use the push and pull_request event trigger
on:
  push:
    branches:
      - arm64_test
  pull_request:
    branches:
      - arm64_test

env:
  USER: github.actor

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ariefak/ros-noetic-desktop:arm64
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:

    - name: Clean workspace
      run: |
        cd ~/sarax_ws/
        . /opt/ros/$ROS_DISTRO/setup.sh
        catkin clean --yes

    - name: Build workspace
      if: always()
      run: |
        cd ~/sarax_ws/
        . /opt/ros/$ROS_DISTRO/setup.sh
        catkin build
