name: Setup and build packages

# To manually run the workflow on GH, use the workflow_dispatch event trigger
# on: workflow_dispatch

# To automatically run on every push to GH, use the push and pull_request event trigger
on:
  push:
    branches:
      - arm64_test
  pull_request:
    branches:
      - arm64_test

env:
  USER: github.actor

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dustynv/ros:noetic-desktop-l4t-r35.4.1
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:

    - name: Maximize build disk space
      uses: easimon/maximize-build-space@v10

    - name: Check environment
      run: |
        export
        ulimit -a

    - name: Update ROS dependencies
      run: |
        . /opt/ros/$ROS_DISTRO/setup.sh
        rosdep update

    - name: Create dependency workspace
      run: |
        mkdir -p ~/dependencies
        cd ~/dependencies
    
    - name: Install PX4 Dependencies
      run: |
        mkdir -p ~/dependencies
        cd ~/dependencies
        wget https://raw.githubusercontent.com/PX4/PX4-Autopilot/main/Tools/setup/ubuntu.sh
        wget https://raw.githubusercontent.com/PX4/PX4-Autopilot/main/Tools/setup/requirements.txt
        chmod +x ~/dependencies/ubuntu.sh && sed -i -e '/g++-multilib \\\/d' -e '/gcc-multilib \\\/d' ubuntu.sh
        . ~/dependencies/ubuntu.sh

    - name: Install MAVROS using binaries
      run: |
        mkdir -p ~/dependencies
        cd ~/dependencies
        sudo apt-get install ros-$ROS_DISTRO-mavros ros-$ROS_DISTRO-mavros-extras

    - name: Install ROS building dependencies
      run: |
        sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential -y
        sudo apt install python3-catkin-tools python3-rosinstall-generator python3-osrf-pycommon -y
        sudo apt-get install ros-$ROS_DISTRO-rqt ros-$ROS_DISTRO-rqt-common-plugins -y
        pip install scipy

    - name: Create new workspace
      run: |
        cd ~
        mkdir -p sarax_ws/src

    - name: Initialise catkin workspace
      run: |
        cd ~/sarax_ws/
        . /opt/ros/$ROS_DISTRO/setup.sh
        catkin init
        wstool init src
    
    - name: Clone Sarax project
      run: |
        cd ~/sarax_ws/src
        git clone --single-branch --branch arm64_test ${{ github.server_url }}/${{ github.repository }}.git
        ls -l

    - name: Get dependencies using rosdep
      run: |
        cd ~/sarax_ws/
        . /opt/ros/$ROS_DISTRO/setup.sh
        rosdep install --from-paths src --ignore-src -r -y --skip-keys="python-scipy"

    - name: Build workspace
      if: always()
      run: |
        cd ~/sarax_ws/
        . /opt/ros/$ROS_DISTRO/setup.sh
        catkin build