name: Publish docker image as package

# To manually run the workflow on GH, use the workflow_dispatch event trigger
# on: workflow_dispatch

# To test workflow using act, use the push event
on:
  push:
    branches:
      - main

# To automatically run depending on the status of the build.yaml workflow, use workflow_run event trigger
# on:
#   workflow_run:
#     workflows: [Setup and build packages]
#     types: [completed]

jobs:
  # on-success:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - run: echo 'The build workflows have passed'
  
  # on-failure:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  #   steps:
  #     - run: echo 'The build workflows have failed'

  publish_package:
    #needs: on-success             # Uncomment when on default branch (main)
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/SaxionMechatronics/sarax:latest

      # - name: Login to GH container registry
      #   run: |
      #     docker login --username saxionmechatronics --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
      
      # - name: Cleanup system
      #   run: |
      #     docker image prune

      # - name: Build Docker image
      #   run: |
      #     docker build --no-cache . -t ghcr.io/saxionmechatronics/sarax-framework:latest

      # - name: Publish image
      #   run: |
      #     docker push ghcr.io/saxionmechatronics/sarax-framework:latest