name: Publish docker image as package
# Uncomment when debugging
on:
  push:
    branches:
      - main

# Comment when debugging
# on:
#   workflow_run:
#     workflows: [Setup and build packages]
#     types: [completed]

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GH container registry
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Cleanup system
        run: |
          docker image prune

      - name: Build Docker image
        run: |
          docker build --no-cache . -t ghcr.io/arief-ak/sarax-framework:latest

      - name: Publish image
        run: |
          docker push ghcr.io/arief-ak/sarax-framework:latest